name: Add Build Status Badge
# This workflow adds a build status badge to the repository
on:
  push:
    branches:
      - main

jobs:
  add_badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate build status badge
        run: |
          echo "![Build Status](https://github.com/${{ github.repository }}/actions/workflows/ci.yml/badge.svg)" > build-status-badge.md

      - name: Commit build status badge
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"          
          git config --global user.name "${{ github.actor }}"
          git add build-status-badge.md
          git commit -m "Add build status badge"
          git push
    env:
      GITHUB_TOKEN: ${{ secrets.PAT_LTD_REPO }}
