name: Add Build Status Badge

on:
  push:
    branches:
      - main

jobs:
  add_badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate build status badge
        run: |
          echo "![Build Status](https://github.com/${{ github.repository }}/actions/workflows/ci.yml/badge.svg)" > build-status-badge.md

      - name: Commit build status badge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add build-status-badge.md
          git commit -m "Add build status badge"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
